### ISSUE TITLE
errror?

### ISSUE THREAD

**Issue by Yuri-Neko** [Julius-Ulee/King-Genshin-StarRail-Stats#2]
Run python main.py -o README.md
Traceback (most recent call last):
  File "/home/runner/work/King-Genshin-StarRail-Stats/King-Genshin-StarRail-Stats/main.py", line [12](https://github.com/Yuri-Neko/King-Genshin-StarRail-Stats/actions/runs/5425907347/jobs/9867403774#step:5:13), in <module>
    import genshin
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/genshin/__init__.py", line 9, in <module>
    from . import models, utility
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/genshin/models/__init__.py", line 2, in <module>
    from .genshin import *
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/genshin/models/genshin/__init__.py", line 2, in <module>
    from .calculator import *
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/genshin/models/genshin/calculator.py", line 9, in <module>
    from genshin.models.model import Aliased, APIModel, Unique
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/genshin/models/model.py", line 37, in <module>
    class APIModel(pydantic.BaseModel, abc.ABC):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/genshin/models/model.py", line 126, in APIModel
    @pydantic.root_validator()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line [22](https://github.com/Yuri-Neko/King-Genshin-StarRail-Stats/actions/runs/5425907347/jobs/9867403774#step:5:23)8, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0/u/root-validator-pre-skip
Error: Process completed with exit code 1.

**Comment by 0zunu** [comment]
You can add `pydantic==1.*`
